server:
  port: 8889
spring:
  application:
    name: microservice-provider
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: a
    url: jdbc:mysql://localhost:3306/testmis81?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=Hongkong
  #security:
    #  user:
    #  name: admin
    # password: a
    #  roles:
    # - USER
mybatis:
  configuration:
    map-underscore-to-camel-case: true    #将_转为驼峰命名
mapper:
  identity: MYSQL   # 标识列用mysql  配置主键自动增长
logging:
  level:
    com.yc.springcloud_detail: debug

eureka:
  client:
    service-url:
      #defaultZone: http://localhost:7001/eureka
      #绕过登录页面，要在eureka中加一个类关闭csrf
      #defaultZone: http://admin:a@localhost:7001/eureka
      defaultZone: http://admin:a@eureka1:7001/eureka,http://admin:a@eureka2:7002/eureka,http://admin:a@eureka3:7003/eureka
  instance:
    instance-id: miscoservice-provider-product_2  #实例名
    #再解决provider端的心跳问题:
    lease-expiration-duration-in-seconds: 90 #如果现在超过了5s的时间间隔( default: 90 s )
    lease-renewal-interval-in-seconds: 30   #设置心跳的时间间隔( default:30s )

#监控配置
info:
  app.name: MICROSERVICE-PROVIDER
  company.name: yc
  build.artifactId: $project.artifactId$
  build.modelVersion: $project.modelVersion$
