server:
  port: 7001
spring:
    security:
      user:
        name: admin
        password: a
eureka:
  instance:
    hostname: eureka1
  client:   #解决  eureka启动时报错的问题, 因为这个服务器启动时，要到别的服务器上去拉取注册信息，同时注册自己
    #fetch-registry: false  #要不要去注册中心获取其他服务的地址 , 解决eureka启动时报错
    #register-with-eureka: false #是否当前客户端要注册到eureka
    service-url:
      defaultZone: http://admin:a@eureka1:7001,http://admin:a@eureka2:7002,http://admin:a@eureka3:7003
  server:
    eviction-interval-timer-in-ms: 60000    #设置清理的间隔时间，ms (默认是60秒）
    enable-self-preservation: true    #设置为false表示关闭保护模式,在保护模式下，如因为网络或其它问题服务提供者掉线的话，eureka不会立即清空服务列表.